### ISSUE TITLE
询问~

### ISSUE THREAD

**Issue by mejustme** [ecomfe/echarts-doc#1]
hi,问下example实例实时编辑那部分是否有开源打算？谢谢~

**Comment by Ovilia** [comment]
点“编辑实例”不就能看到源码了吗？

**Comment by mejustme** [comment]
女神真淘气，是gitbug工程中的，不是页面上的。那个链接请求的页面不在这个工程中呢

**Comment by Ovilia** [comment]
不太明白你为什么想看这个？暂时没有开源哦~

**Comment by mejustme** [comment]
好的，谢谢哈~
