### ISSUE TITLE
Can you tell me how to run './dashing build echarts -f dashing-cn.json -s ./cn.'

### ISSUE THREAD

**Issue by Richard-Miao2000** [ecomfe/echarts-doc#12]
The readme write below info, but I don't know how to run the commands.

Build

To build Docset in English: ./dashing build echarts -f dashing-en.json -s ./en.
To build Docset in Chinese: ./dashing build echarts -f dashing-cn.json -s ./cn.

**Comment by Ovilia** [comment]
This is used to build [Dash](https://kapeli.com/dash) offline doc. I don't think you may need it unless to update the Dash doc.
If you need to build ECharts doc, follow instructions in `Build and Run Locally`.

**Comment by Richard20160601** [comment]
Because my compony can't access internet, I want run document server for devs. But the default version is english, so I want build chinese version.

**Comment by Ovilia** [comment]
@Richard-Miao2000 For local build, see: https://github.com/ecomfe/echarts-doc#build-and-run-locally .
