### ISSUE TITLE
Gallery links should be HTTPS

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts-doc#2]
I'm getting this error when accessing echarts docs on github: 
![image](https://cloud.githubusercontent.com/assets/561365/17394499/c2788510-5a29-11e6-890e-dcc2f8055b29.png)

This happens as https://ecomfe.github.io is automatically switched to HTTPS

One thing that would be great is to put the gallery into github as well so it can all be loaded from github CDN. There are some issues with accessing content from http://echarts.baidu.com as it can be very slow or inaccessible at times during day here in Europe. 

Anyway thanks so much for translating docs into English!

**Comment by Ovilia** [comment]
Thanks for report. What is the URL of this error?

**Comment by jarben** [comment]
Hi Olivia, one example is: 
https://ecomfe.github.io/echarts-doc/public/api-en.html#echartsInstance.setOption

Another one: https://ecomfe.github.io/echarts-doc/public/option-en.html#title

Although the second url hasn't been reviewed yet:)

Also, would be generally very helpful if your gallery is an open source repository:)

Thanks for looking at this!

**Comment by pissang** [comment]
Already fixed.
