### ISSUE TITLE
effectScatter is missing from online builder

### ISSUE THREAD

**Issue by kelvinau** [ecomfe/echarts-doc#26]
Chart effectScatter is missing from the builder.
I am trying to create a PR for this (https://github.com/kelvinau/echarts-doc/commit/4bafaa1f988034178f65b5d4408900c607c6b5cb), but I don't have the svg icon your team makes for effectScatter. The file structure of cn is also different from en.

![2018-07-11 06_56_40-echarts online builder](https://user-images.githubusercontent.com/5885902/42576564-89e1dd5c-84d7-11e8-97a5-d79f8fb6115e.png)

**Comment by Ovilia** [comment]
Thanks for your PR. But I'm afraid we have to change the source file rather than the built file. I will follow up. Thanks!
