### ISSUE TITLE
Charts / code is not loading on docs page

### ISSUE THREAD

**Issue by danieldeicide** [ecomfe/echarts-doc#27]
Hi!

Charts / code is not loaded on [docs page](https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Custom%20Series). Could you please check and fix?

I really love your work, btw.

Cheers!

**Comment by Ovilia** [comment]
@danieldeicide Thanks for your report. That should be a mistake. I'll fix it later. Thanks!
