### ISSUE TITLE
Insufficient Documentation

### ISSUE THREAD

**Issue by bojidaryovchev** [ecomfe/echarts-doc#30]
Hello there! So the problem is that in the examples there are some things that work with the latest version but are not present in the docs such as graphic.LinearGradient().. I couldn't find documentation for it anywhere and I have no idea what the parameters stand for.. Could you provide me with some information or point me out to some v3 or v2 docs where I can check it out? Thanks in advance!

**Comment by Justineo** [comment]
As I understand this API is from ZRender's [`LinearGradient`](https://ecomfe.github.io/zrender-doc/public/api.html#zrenderlineargradient). Is it right @Ovilia? And ZRender currently doesn't have English docs yet but [Google Translate](https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fecomfe.github.io%2Fzrender-doc%2Fpublic%2Fapi.html%23zrenderlineargradient&edit-text=) might offer help.

**Comment by bojidaryovchev** [comment]
thanks a lot, seems to be it.. anyway, it would be good for it to be incorporated into the echarts docs since its part of its out of the box functionality

**Comment by Ovilia** [comment]
@bojidaryovchev Hi. Sorry for the misunderstanding.
We did not provide the doc for `graphic.LinearGradient` because it is suggest to use this instead, which can be found at [#series-line.itemStyle.color](http://echarts.apache.org/option.html#series-line.itemStyle.color):

```js
color: {
    type: 'linear',
    x: 0,
    y: 0,
    x2: 0,
    y2: 1,
    colorStops: [{
        offset: 0, color: 'red' // color at 0% position
    }, {
        offset: 1, color: 'blue' // color at 100% position
    }],
    globalCoord: false // false by default
}
```
