### ISSUE TITLE
Documentation Site Currently Issuing API Key Error

### ISSUE THREAD

**Issue by derricksimpson** [ecomfe/echarts-doc#34]
While viewing the Tutorial, API, or Option pages - we are getting a modal alert related to an API for each/every chart that gets rendered on the page.

Thanks!

![image](https://user-images.githubusercontent.com/656292/51754690-f46ef980-208a-11e9-95fc-bc1746cc4991.png)

**Comment by Ovilia** [comment]
Could you please provide a URL for this?

**Comment by derricksimpson** [comment]
Sorry about that. Here it is:
https://echarts.apache.org/option.html#timeline

It actually looks like this is not happening anymore.

**Comment by Ovilia** [comment]
All right. I'm going to close this issue. Feel free to open again if it has future problems.
