### ISSUE TITLE
Examples in this repo?

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts-doc#4]
Hi ECharts team, not sure whether this request falls into this repo but is there any way to publish your echarts.baidu.com/examples.html page on github similarly to this repo? The issue is that in some hours of day, pages from baidu.com can't be loaded for some reason.. or it's very slow to load it.

**Comment by pissang** [comment]
Hi @jarben , we have just moved example repo to github. Please feel free to check it out. 
https://github.com/ecomfe/echarts-examples

**Comment by jarben** [comment]
THIS IS AWESOME, thanks heaps @pissang !
